// Code generated by "generate_embedded"; DO NOT EDIT.
package main

var indexHTML = "<html>\n<form><input name=\"user\" placeholder=\"user\"></form>\n\n{{with .}}\n<p>found {{.TotalCount}} comments in {{.Duration}}</p>\n{{range .Comments}}\n    <li>{{.GC.Created.Format \"2006-01-02 15:04:05\"}} on <a href='{{printf \"https://github.com/%s/issues/%d#issuecomment-%d\" .GR.ID .GI.Number .GC.ID}}'>{{.GR.ID}}: {{.GI.Title}}</a></li>\n{{end}}\n{{end}}\n</html>"
